export const MAX_FREE_TRIES = 3

export const JUDGE_MODEL = 'openai/gpt-oss-120b'

export const PASSWORD_HASH = '8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918'

export const MODELS = [
  { id: 'openai/gpt-oss-120b', name: 'GPT-OSS 120B', provider: 'Groq', description: 'OpenAI open-weight reasoning model served through Groq.', tags: ['Hosted', 'Reasoning', 'Fast'], contextWindow: '131K', country: 'USA' },
  { id: 'openai/gpt-oss-20b', name: 'GPT-OSS 20B', provider: 'Groq', description: 'Smaller OpenAI open-weight reasoning model served through Groq.', tags: ['Hosted', 'Reasoning', 'Very Fast'], contextWindow: '131K', country: 'USA' },
]

export const METRICS = [
  { id: 'accuracy', label: 'Accuracy' },
  { id: 'clarity', label: 'Clarity' },
  { id: 'completeness', label: 'Completeness' },
  { id: 'coding', label: 'Coding' },
  { id: 'reasoning', label: 'Reasoning' },
  { id: 'research', label: 'Research' },
  { id: 'finance', label: 'Finance' },
  { id: 'accounting', label: 'Accounting' },
]

export const PROMPT_TEMPLATES = [
  { id: 'reasoning', label: 'Reasoning', prompt: 'Analyze this problem step by step. State the key assumptions, compare the possible approaches, and give a concise final conclusion. Problem: A college has 1,200 students. Every student must attend at least 75% of lectures. In one semester there are 96 scheduled lectures. Student A attended 78, Student B attended 72, and Student C attended 90. Calculate each attendance percentage, identify who satisfies the requirement, and explain whether attending 6 additional lectures would change Student B\'s status.' },
  { id: 'coding', label: 'Coding', prompt: 'Build a production-ready TypeScript solution for this task. Include the implementation, explain the time and space complexity, handle edge cases, and provide tests. Task: Given an array of meeting intervals such as [[1,3],[2,6],[8,10],[9,12],[15,18]], merge every overlapping interval and return the minimum set of non-overlapping intervals. The input may be unsorted, may contain duplicate intervals, and may contain intervals where start equals end. Do not mutate the original array.' },
  { id: 'math', label: 'Math', prompt: 'Solve the following mathematical problem. Show the important derivation steps, verify the result independently, and give the final answer clearly. Problem: A box contains 5 red balls, 4 blue balls, and 3 green balls. Three balls are drawn uniformly at random without replacement. What is the probability that exactly two of the three drawn balls have the same color? Express the answer as a simplified fraction and decimal.' },
  { id: 'research', label: 'Research', prompt: 'Prepare a technical research brief based on established knowledge. Clearly separate stable facts from version-sensitive claims and identify what should be verified from current documentation. Topic: Compare PostgreSQL, MySQL, and SQLite for a multi-tenant college ERP serving about 50,000 students and 2,000 staff, with role-based access control, attendance, timetable updates, audit logs, reporting, backups, and concurrent users. Compare transactions, concurrency, realtime/event support, extensions, deployment, licensing, operational complexity, and scaling. Finish with a neutral decision framework rather than choosing a winner.' },
  { id: 'summarization', label: 'Summarization', prompt: 'Summarize the following text in three layers: a one-sentence summary, five key points, and important details that should not be lost. Text: A college management platform is being redesigned as a single cloud application for academic, administrative, financial, and operational workflows. The proposed system includes student and staff records, guardian-faculty mentoring, attendance, dynamic timetables, syllabus completion tracking, academic monitoring, biometric staff attendance, role-based access control, and dashboards for administrators, faculty, students, and guardians. The design goal is to reduce duplicate data entry and give each role realtime visibility into information relevant to its responsibilities. The team also wants an AI assistant that can answer questions using ERP data while keeping sensitive information protected. The platform is planned with a modern web frontend, a managed PostgreSQL database, and server-side APIs.' },
  { id: 'translation', label: 'Translation', prompt: 'Translate the following English text into French, Hindi, Chinese, and German. Preserve meaning, tone, technical terms, numbers, and paragraph structure. Text: Our college ERP will provide a realtime dashboard for attendance, timetable changes, syllabus progress, student mentoring, and staff operations. Administrators can review reports, faculty can manage academic activities, students can monitor their own progress, and guardians can receive relevant updates. The system should remain simple to use while enforcing role-based access to sensitive information.' },
  { id: 'creative', label: 'Creative', prompt: 'Create three distinct versions of the following announcement: professional, friendly, and highly creative. Keep each version under 100 words and explain the tone in one sentence. Brief: We are launching an AI Model Evaluation Dashboard that lets users submit one prompt and compare multiple language models side by side on response quality, latency, token usage, cost, and task-specific evaluation scores. The launch message should make developers and students curious enough to try it.' },
  { id: 'data', label: 'Data Analysis', prompt: 'Analyze the following dataset. Identify trends, anomalies, relationships, and actionable insights. Show calculations where useful and state limitations. Data: Month,Active Users,API Requests,Avg Latency Ms,Error Rate Percent. Jan,1200,18000,820,4.2. Feb,1380,21000,760,3.8. Mar,1510,26000,710,3.1. Apr,1490,31000,890,4.9. May,1760,36000,680,2.7. Jun,1980,42000,640,2.2. Calculate user growth from January to June, request growth, average latency change, error-rate change, identify any unusual month, and explain whether higher traffic appears associated with lower or higher latency in this dataset.' },
  { id: 'finance', label: 'Finance', prompt: 'Analyze this financial scenario using explicit assumptions. Show the calculations and do not invent missing facts. Scenario: A SaaS product has monthly revenue of ₹12,00,000. Variable operating costs are ₹3,20,000 per month, fixed operating costs are ₹4,50,000 per month, and payment processing fees are 2.5% of revenue. The company wants to add a feature costing ₹1,20,000 per month in additional fixed expenses. Calculate the current monthly operating contribution after variable costs and payment fees, the contribution after the new feature, the break-even monthly revenue after the feature, and the percentage change in operating contribution. State at least three financial risks or assumptions that management should validate.' },
  { id: 'instruction', label: 'Instruction', prompt: 'Follow these instructions exactly. Return ONLY a JSON array of five objects with the keys id, priority, category, and reason. Do not add markdown or commentary. Classify these support tickets: 1) "The student cannot log in after changing the password." 2) "The timetable shows two lectures in the same room at 10 AM." 3) "The attendance percentage for student 1042 is 68%, but the faculty register says 74%." 4) "The fee receipt PDF downloads with the wrong student name." 5) "The dashboard takes more than 8 seconds to load." Use priority values High, Medium, or Low. Use categories Authentication, Timetable, Attendance, Fees, or Performance. Assign each ticket one priority and one category, and give a one-sentence reason.' },
]

export const PRICING = Object.fromEntries(MODELS.map((model) => [model.id, { input: 0, output: 0 }]))
