export const MAX_FREE_TRIES = 3

export const MODELS = [
  { id: 'openrouter/free', name: 'OpenRouter Free Router', provider: 'OpenRouter', description: 'Automatically routes each request to an available free OpenRouter model.', tags: ['Free', 'Auto-route', 'Open'], contextWindow: '200K+', country: 'Global' },
  { id: 'nvidia/nemotron-3-ultra-550b-a55b:free', name: 'Nemotron 3 Ultra', provider: 'OpenRouter', description: 'NVIDIA open frontier reasoning model for coding, research, planning and complex enterprise tasks.', tags: ['USA', 'Free', 'Reasoning', 'Open-weight'], contextWindow: '1M', country: 'USA' },
  { id: 'nvidia/nemotron-3.5-lightning:free', name: 'Nemotron 3.5 Lightning', provider: 'OpenRouter', description: 'NVIDIA open MoE model optimized for fast, high-throughput agentic workloads.', tags: ['USA', 'Free', 'Fast', 'Open-weight'], contextWindow: '1M', country: 'USA' },
  { id: 'deepseek/deepseek-v4-flash-0731:free', name: 'DeepSeek V4 Flash', provider: 'OpenRouter', description: 'DeepSeek open-weight MoE model for coding, reasoning and agent workflows.', tags: ['China', 'Free', 'Coding', 'Reasoning'], contextWindow: '1M', country: 'China' },
  { id: 'qwen/qwen3.8-27b:free', name: 'Qwen3.8 27B', provider: 'OpenRouter', description: 'Qwen open-weight multimodal model for coding, research, professional workflows and multilingual work.', tags: ['China', 'Free', 'Multilingual', 'Open-weight'], contextWindow: '262K', country: 'China' },
  { id: 'z-ai/glm-5.2:free', name: 'GLM 5.2', provider: 'OpenRouter', description: 'Z.ai reasoning model for long-horizon software engineering and multi-step automation.', tags: ['China', 'Free', 'Coding', 'Reasoning'], contextWindow: '32K', country: 'China' },
  { id: 'inclusionai/ling-3.0-flash:free', name: 'Ling 3.0 Flash', provider: 'OpenRouter', description: 'InclusionAI open MoE model focused on token efficiency and production-scale agentic inference.', tags: ['China', 'Free', 'Fast', 'Open-weight'], contextWindow: '262K', country: 'China' },
  { id: 'inclusionai/ling-3.0-flash-sante:free', name: 'Ling 3.0 Flash Sante', provider: 'OpenRouter', description: 'InclusionAI specialized open model for health and medical knowledge reasoning.', tags: ['China', 'Free', 'Medical', 'Reasoning'], contextWindow: '262K', country: 'China' },
  { id: 'inclusionai/ling-3.0-flash-fin:free', name: 'Ling 3.0 Flash Fin', provider: 'OpenRouter', description: 'InclusionAI finance-focused open model for investment workflows, mathematics and planning.', tags: ['China', 'Free', 'Finance', 'Reasoning'], contextWindow: '262K', country: 'China' },
  { id: 'google/gemma-4-26b-a4b-it:free', name: 'Gemma 4 26B A4B', provider: 'OpenRouter', description: 'Google DeepMind open model with efficient MoE inference, reasoning, coding and multilingual support.', tags: ['USA', 'Free', 'Open-weight', 'Multimodal'], contextWindow: '262K', country: 'USA' },
  { id: 'thinkingmachines/inkling:free', name: 'Inkling', provider: 'OpenRouter', description: 'Open-weight multimodal model for reasoning, coding, agentic workflows and multilingual conversation.', tags: ['USA', 'Free', 'Multilingual', 'Open-weight'], contextWindow: '1M', country: 'USA' },
  { id: 'thinkingmachines/inkling-small:free', name: 'Inkling Small', provider: 'OpenRouter', description: 'Smaller open-weight multimodal model for reasoning, coding, instruction following and multilingual tasks.', tags: ['USA', 'Free', 'Small', 'Multilingual'], contextWindow: '1M', country: 'USA' },
  { id: 'openai/gpt-5.6-sol', name: 'GPT-5.6 Sol', provider: 'OpenRouter', description: 'OpenAI model for complex reasoning, coding, and professional work.', tags: ['USA', 'Hosted', 'Reasoning'], contextWindow: '1.05M', country: 'USA' },
  { id: 'openai/gpt-5.6-terra', name: 'GPT-5.6 Terra', provider: 'OpenRouter', description: 'OpenAI GPT-5.6 model focused on balancing intelligence and cost.', tags: ['USA', 'Hosted', 'Coding'], contextWindow: '1.05M', country: 'USA' },
  { id: 'anthropic/claude-fable-5.1', name: 'Claude Fable 5.1', provider: 'OpenRouter', description: 'Anthropic model for agentic coding, knowledge work, and finance analysis.', tags: ['USA', 'Hosted', 'Coding'], contextWindow: '1M', country: 'USA' },
  { id: 'anthropic/claude-opus-5', name: 'Claude Opus 5', provider: 'OpenRouter', description: 'Anthropic model for demanding reasoning, coding, and long-horizon work.', tags: ['USA', 'Hosted', 'Reasoning'], contextWindow: '1M', country: 'USA' },
  { id: 'openai/gpt-oss-120b', name: 'GPT-OSS 120B', provider: 'Groq', description: 'Open-weight model served through Groq for fast reasoning and tool use.', tags: ['USA', 'Open-weight', 'Fast'], contextWindow: '131K', country: 'USA' },
  { id: 'openai/gpt-oss-20b', name: 'GPT-OSS 20B', provider: 'Groq', description: 'Open-weight model served through Groq for very fast inference.', tags: ['USA', 'Open-weight', 'Very Fast'], contextWindow: '131K', country: 'USA' },
]

export const PRICING = {
  'openrouter/free': { input: 0, output: 0 },
  'nvidia/nemotron-3-ultra-550b-a55b:free': { input: 0, output: 0 },
  'nvidia/nemotron-3.5-lightning:free': { input: 0, output: 0 },
  'deepseek/deepseek-v4-flash-0731:free': { input: 0, output: 0 },
  'qwen/qwen3.8-27b:free': { input: 0, output: 0 },
  'z-ai/glm-5.2:free': { input: 0, output: 0 },
  'inclusionai/ling-3.0-flash:free': { input: 0, output: 0 },
  'inclusionai/ling-3.0-flash-sante:free': { input: 0, output: 0 },
  'inclusionai/ling-3.0-flash-fin:free': { input: 0, output: 0 },
  'google/gemma-4-26b-a4b-it:free': { input: 0, output: 0 },
  'thinkingmachines/inkling:free': { input: 0, output: 0 },
  'thinkingmachines/inkling-small:free': { input: 0, output: 0 },
  'openai/gpt-5.6-sol': { input: 0.002, output: 0.01 },
  'openai/gpt-5.6-terra': { input: 0.002, output: 0.012 },
  'anthropic/claude-fable-5.1': { input: 0.01, output: 0.05 },
  'anthropic/claude-opus-5': { input: 0.005, output: 0.025 },
  'openai/gpt-oss-120b': { input: 0.00015, output: 0.0006 },
  'openai/gpt-oss-20b': { input: 0.000075, output: 0.0003 },
}
