export const MAX_FREE_TRIES = 3

export const MODELS = [
  { id: 'openrouter/free', name: 'OpenRouter Free Router', provider: 'OpenRouter', description: 'Automatically routes each request to an available free OpenRouter model.', tags: ['Free', 'Auto-route', 'Open'], contextWindow: '200K+', country: 'Global' },
  { id: 'nvidia/nemotron-3-ultra-550b-a55b:free', name: 'Nemotron 3 Ultra', provider: 'OpenRouter', description: 'NVIDIA open frontier reasoning model for coding, research, planning and complex enterprise tasks.', tags: ['USA', 'Free', 'Reasoning', 'Open-weight'], contextWindow: '1M', country: 'USA' },
  { id: 'nvidia/nemotron-3.5-lightning:free', name: 'Nemotron 3.5 Lightning', provider: 'OpenRouter', description: 'NVIDIA open MoE model optimized for fast, high-throughput agentic workloads.', tags: ['USA', 'Free', 'Fast', 'Open-weight'], contextWindow: '1M', country: 'USA' },
  { id: 'deepseek/deepseek-v4-flash-0731:free', name: 'DeepSeek V4 Flash', provider: 'OpenRouter', description: 'DeepSeek open-weight MoE model for coding, reasoning and agent workflows.', tags: ['China', 'Free', 'Coding', 'Reasoning'], contextWindow: '1M', country: 'China' },
  { id: 'qwen/qwen3.8-27b:free', name: 'Qwen3.8 27B', provider: 'OpenRouter', description: 'Qwen open-weight multimodal model for coding, research, professional workflows and multilingual work.', tags: ['China', 'Free', 'Multilingual', 'Open-weight'], contextWindow: '262K', country: 'China' },
  { id: 'z-ai/glm-5.2:free', name: 'GLM 5.2', provider: 'OpenRouter', description: 'Z.ai reasoning model for long-horizon software engineering and multi-step automation.', tags: ['China', 'Free', 'Coding', 'Reasoning'], contextWindow: '32K', country: 'China' },
  { id: 'inclusionai/ling-3.0-flash:free', name: 'Ling 3.0 Flash', provider: 'OpenRouter', description: 'InclusionAI open MoE model focused on token efficiency and production-scale agentic inference.', tags: ['China', 'Free', 'Fast', 'Open-weight'], contextWindow: '262K', country: 'China' },
  { id: 'inclusionai/ling-3.0-flash-sante:free', name: 'Ling 3.0 Flash Sante', provider: 'OpenRouter', description: 'InclusionAI specialized open model for health and medical knowledge reasoning.', tags: ['China', 'Free', 'Medical', 'Reasoning'], contextWindow: '262K', country: 'China' },
  { id: 'inclusionai/ling-3.0-flash-fin:free', name: 'Ling 3.0 Flash Fin', provider: 'OpenRouter', description: 'InclusionAI finance-focused open model for investment workflows, mathematics and planning.', tags: ['China', 'Free', 'Finance', 'Reasoning'], contextWindow: '262K', country: 'China' },
  { id: 'google/gemma-4-26b-a4b-it:free', name: 'Gemma 4 26B A4B', provider: 'OpenRouter', description: 'Google DeepMind open model with efficient MoE inference, reasoning, coding and multilingual support.', tags: ['USA', 'Free', 'Open-weight', 'Multimodal'], contextWindow: '262K', country: 'USA' },
  { id: 'thinkingmachines/inkling:free', name: 'Inkling', provider: 'OpenRouter', description: 'Open-weight multimodal model for reasoning, coding, agentic workflows and multilingual conversation.', tags: ['USA', 'Free', 'Multilingual', 'Open-weight'], contextWindow: '1M', country: 'USA' },
  { id: 'thinkingmachines/inkling-small:free', name: 'Inkling Small', provider: 'OpenRouter', description: 'Smaller open-weight multimodal model for reasoning, coding, instruction following and multilingual tasks.', tags: ['USA', 'Free', 'Small', 'Multilingual'], contextWindow: '1M', country: 'USA' },
  { id: 'openai/gpt-5.6-sol', name: 'GPT-5.6 Sol', provider: 'OpenRouter', description: 'OpenAI model for complex reasoning, coding, and professional work.', tags: ['USA', 'Hosted', 'Reasoning'], contextWindow: '1.05M', country: 'USA' },
  { id: 'openai/gpt-5.6-terra', name: 'GPT-5.6 Terra', provider: 'OpenRouter', description: 'OpenAI GPT-5.6 model focused on balancing intelligence and cost.', tags: ['USA', 'Hosted', 'Coding'], contextWindow: '1.05M', country: 'USA' },
  { id: 'anthropic/claude-fable-5.1', name: 'Claude Fable 5.1', provider: 'OpenRouter', description: 'Anthropic model for agentic coding, knowledge work, and finance analysis.', tags: ['USA', 'Hosted', 'Coding'], contextWindow: '1M', country: 'USA' },
  { id: 'anthropic/claude-opus-5', name: 'Claude Opus 5', provider: 'OpenRouter', description: 'Anthropic model for demanding reasoning, coding, and long-horizon work.', tags: ['USA', 'Hosted', 'Reasoning'], contextWindow: '1M', country: 'USA' },
  { id: 'openai/gpt-oss-120b', name: 'GPT-OSS 120B', provider: 'Groq', description: 'Open-weight model served through Groq for fast reasoning and tool use.', tags: ['USA', 'Open-weight', 'Fast'], contextWindow: '131K', country: 'USA' },
  { id: 'openai/gpt-oss-20b', name: 'GPT-OSS 20B', provider: 'Groq', description: 'Open-weight model served through Groq for very fast inference.', tags: ['USA', 'Open-weight', 'Very Fast'], contextWindow: '131K', country: 'USA' },
]

  { id: 'google/gemini-2.5-flash-lite', name: 'Gemini 2.5 Flash-Lite', provider: 'Google AI', description: 'Google Gemini API free-tier model for fast general-purpose evaluation.', tags: ['Google', 'Free', 'Fast'], contextWindow: '1M', country: 'USA' },
  { id: 'google/gemini-3.8-flash', name: 'Gemini 3.8 Flash', provider: 'Google AI', description: 'Google Gemini Flash model with a documented free API tier.', tags: ['Google', 'Free', 'Reasoning'], contextWindow: '1M', country: 'USA' },
  { id: 'hf/deepseek-ai/DeepSeek-R1', name: 'DeepSeek R1 via Hugging Face', provider: 'Hugging Face', description: 'Hugging Face routed inference with a monthly free credit for experimentation.', tags: ['Hugging Face', 'Free Credit', 'Reasoning'], contextWindow: '163K', country: 'Global' },
  { id: 'hf/Qwen/Qwen3-Next-80B-A3B-Instruct', name: 'Qwen3 Next 80B via Hugging Face', provider: 'Hugging Face', description: 'Hugging Face routed open-model inference for coding and reasoning.', tags: ['Hugging Face', 'Free Credit', 'China'], contextWindow: '262K', country: 'China' },
  { id: 'cloudflare/@cf/meta/llama-3.2-1b-instruct', name: 'Llama 3.2 1B via Cloudflare', provider: 'Cloudflare AI', description: 'Workers AI model available within Cloudflare Free plan daily allocation.', tags: ['Cloudflare', 'Free', 'Small'], contextWindow: '8K', country: 'USA' },
  { id: 'cloudflare/@cf/qwen/qwen1.5-14b-chat-awq', name: 'Qwen 1.5 14B via Cloudflare', provider: 'Cloudflare AI', description: 'Open Qwen model served by Cloudflare Workers AI.', tags: ['Cloudflare', 'Free', 'China'], contextWindow: '32K', country: 'China' },
  { id: 'nvidia/deepseek-v4.1-flash', name: 'DeepSeek V4.1 Flash via NVIDIA', provider: 'NVIDIA NIM', description: 'NVIDIA Build free endpoint for DeepSeek V4.1 Flash.', tags: ['NVIDIA', 'Free Endpoint', 'China'], contextWindow: '1M', country: 'China' },
  { id: 'nvidia/glm-5-3-flash', name: 'GLM 5.3 Flash via NVIDIA', provider: 'NVIDIA NIM', description: 'NVIDIA Build free endpoint for Z.ai GLM 5.3 Flash.', tags: ['NVIDIA', 'Free Endpoint', 'China'], contextWindow: '256K', country: 'China' },
export const PRICING = {
  'google/gemini-2.5-flash-lite': { input: 0, output: 0 },
  'google/gemini-3.8-flash': { input: 0, output: 0 },
  'hf/deepseek-ai/DeepSeek-R1': { input: 0, output: 0 },
  'hf/Qwen/Qwen3-Next-80B-A3B-Instruct': { input: 0, output: 0 },
  'cloudflare/@cf/meta/llama-3.2-1b-instruct': { input: 0, output: 0 },
  'cloudflare/@cf/qwen/qwen1.5-14b-chat-awq': { input: 0, output: 0 },
  'nvidia/deepseek-v4.1-flash': { input: 0, output: 0 },
  'nvidia/glm-5-3-flash': { input: 0, output: 0 },
  'openrouter/free': { input: 0, output: 0 },
  'nvidia/nemotron-3-ultra-550b-a55b:free': { input: 0, output: 0 },
  'nvidia/nemotron-3.5-lightning:free': { input: 0, output: 0 },
  'deepseek/deepseek-v4-flash-0731:free': { input: 0, output: 0 },
  'qwen/qwen3.8-27b:free': { input: 0, output: 0 },
  'z-ai/glm-5.2:free': { input: 0, output: 0 },
  'inclusionai/ling-3.0-flash:free': { input: 0, output: 0 },
  'inclusionai/ling-3.0-flash-sante:free': { input: 0, output: 0 },
  'inclusionai/ling-3.0-flash-fin:free': { input: 0, output: 0 },
  'google/gemma-4-26b-a4b-it:free': { input: 0, output: 0 },
  'thinkingmachines/inkling:free': { input: 0, output: 0 },
  'thinkingmachines/inkling-small:free': { input: 0, output: 0 },
  'openai/gpt-5.6-sol': { input: 0.002, output: 0.01 },
  'openai/gpt-5.6-terra': { input: 0.002, output: 0.012 },
  'anthropic/claude-fable-5.1': { input: 0.01, output: 0.05 },
  'anthropic/claude-opus-5': { input: 0.005, output: 0.025 },
  'openai/gpt-oss-120b': { input: 0.00015, output: 0.0006 },
  'openai/gpt-oss-20b': { input: 0.000075, output: 0.0003 },
}export const PROMPT_TEMPLATES = [
  { id: 'reasoning', label: 'Reasoning', prompt: 'Analyze this problem step by step. State the key assumptions, compare the possible approaches, and give a concise final conclusion. Problem: A college has 1,200 students. Every student must attend at least 75% of lectures. In one semester there are 96 scheduled lectures. Student A attended 78, Student B attended 72, and Student C attended 90. Calculate each attendance percentage, identify who satisfies the requirement, and explain whether attending 6 additional lectures would change Student B\'s status.' },
  { id: 'coding', label: 'Coding', prompt: 'Build a production-ready TypeScript solution for this task. Include the implementation, explain the time and space complexity, handle edge cases, and provide tests. Task: Given an array of meeting intervals such as [[1,3],[2,6],[8,10],[9,12],[15,18]], merge every overlapping interval and return the minimum set of non-overlapping intervals. The input may be unsorted, may contain duplicate intervals, and may contain intervals where start equals end. Do not mutate the original array.' },
  { id: 'math', label: 'Math', prompt: 'Solve the following mathematical problem. Show the important derivation steps, verify the result independently, and give the final answer clearly. Problem: A box contains 5 red balls, 4 blue balls, and 3 green balls. Three balls are drawn uniformly at random without replacement. What is the probability that exactly two of the three drawn balls have the same color? Express the answer as a simplified fraction and decimal.' },
  { id: 'research', label: 'Research', prompt: 'Prepare a technical research brief based on established knowledge. Clearly separate stable facts from version-sensitive claims and identify what should be verified from current documentation. Topic: Compare PostgreSQL, MySQL, and SQLite for a multi-tenant college ERP serving about 50,000 students and 2,000 staff, with role-based access control, attendance, timetable updates, audit logs, reporting, backups, and concurrent users. Compare transactions, concurrency, realtime/event support, extensions, deployment, licensing, operational complexity, and scaling. Finish with a neutral decision framework rather than choosing a winner.' },
  { id: 'summarization', label: 'Summarization', prompt: 'Summarize the following text in three layers: a one-sentence summary, five key points, and important details that should not be lost. Text: A college management platform is being redesigned as a single cloud application for academic, administrative, financial, and operational workflows. The proposed system includes student and staff records, guardian-faculty mentoring, attendance, dynamic timetables, syllabus completion tracking, academic monitoring, biometric staff attendance, role-based access control, and dashboards for administrators, faculty, students, and guardians. The design goal is to reduce duplicate data entry and give each role realtime visibility into information relevant to its responsibilities. The team also wants an AI assistant that can answer questions using ERP data while keeping sensitive information protected. The platform is planned with a modern web frontend, a managed PostgreSQL database, and server-side APIs.' },
  { id: 'translation', label: 'Translation', prompt: 'Translate the following English text into French, Hindi, Chinese, and German. Preserve meaning, tone, technical terms, numbers, and paragraph structure. Text: Our college ERP will provide a realtime dashboard for attendance, timetable changes, syllabus progress, student mentoring, and staff operations. Administrators can review reports, faculty can manage academic activities, students can monitor their own progress, and guardians can receive relevant updates. The system should remain simple to use while enforcing role-based access to sensitive information.' },
  { id: 'creative', label: 'Creative', prompt: 'Create three distinct versions of the following announcement: professional, friendly, and highly creative. Keep each version under 100 words and explain the tone in one sentence. Brief: We are launching an AI Model Evaluation Dashboard that lets users submit one prompt and compare multiple language models side by side on response quality, latency, token usage, cost, and task-specific evaluation scores. The launch message should make developers and students curious enough to try it.' },
  { id: 'data', label: 'Data Analysis', prompt: 'Analyze the following dataset. Identify trends, anomalies, relationships, and actionable insights. Show calculations where useful and state limitations. Data: Month,Active Users,API Requests,Avg Latency Ms,Error Rate Percent. Jan,1200,18000,820,4.2. Feb,1380,21000,760,3.8. Mar,1510,26000,710,3.1. Apr,1490,31000,890,4.9. May,1760,36000,680,2.7. Jun,1980,42000,640,2.2. Calculate user growth from January to June, request growth, average latency change, error-rate change, identify any unusual month, and explain whether higher traffic appears associated with lower or higher latency in this dataset.' },
  { id: 'finance', label: 'Finance', prompt: 'Analyze this financial scenario using explicit assumptions. Show the calculations and do not invent missing facts. Scenario: A SaaS product has monthly revenue of ₹12,00,000. Variable operating costs are ₹3,20,000 per month, fixed operating costs are ₹4,50,000 per month, and payment processing fees are 2.5% of revenue. The company wants to add a feature costing ₹1,20,000 per month in additional fixed expenses. Calculate the current monthly operating contribution after variable costs and payment fees, the contribution after the new feature, the break-even monthly revenue after the feature, and the percentage change in operating contribution. State at least three financial risks or assumptions that management should validate.' },
  { id: 'instruction', label: 'Instruction', prompt: 'Follow these instructions exactly. Return ONLY a JSON array of five objects with the keys id, priority, category, and reason. Do not add markdown or commentary. Classify these support tickets: 1) "The student cannot log in after changing the password." 2) "The timetable shows two lectures in the same room at 10 AM." 3) "The attendance percentage for student 1042 is 68%, but the faculty register says 74%." 4) "The fee receipt PDF downloads with the wrong student name." 5) "The dashboard takes more than 8 seconds to load." Use priority values High, Medium, or Low. Use categories Authentication, Timetable, Attendance, Fees, or Performance. Assign each ticket one priority and one category, and give a one-sentence reason.' },
]

export const PRICING = {
  'openrouter/free': { input: 0, output: 0 },
  'nvidia/nemotron-3-ultra-550b-a55b:free': { input: 0, output: 0 },
  'nvidia/nemotron-3.5-lightning:free': { input: 0, output: 0 },
  'deepseek/deepseek-v4-flash-0731:free': { input: 0, output: 0 },
  'qwen/qwen3.8-27b:free': { input: 0, output: 0 },
  'z-ai/glm-5.2:free': { input: 0, output: 0 },
  'inclusionai/ling-3.0-flash:free': { input: 0, output: 0 },
  'inclusionai/ling-3.0-flash-sante:free': { input: 0, output: 0 },
  'inclusionai/ling-3.0-flash-fin:free': { input: 0, output: 0 },
  'google/gemma-4-26b-a4b-it:free': { input: 0, output: 0 },
  'thinkingmachines/inkling:free': { input: 0, output: 0 },
  'thinkingmachines/inkling-small:free': { input: 0, output: 0 },
  'openai/gpt-5.6-sol': { input: 0.002, output: 0.01 },
  'openai/gpt-5.6-terra': { input: 0.002, output: 0.012 },
  'anthropic/claude-fable-5.1': { input: 0.01, output: 0.05 },
  'anthropic/claude-opus-5': { input: 0.005, output: 0.025 },
  'openai/gpt-oss-120b': { input: 0.00015, output: 0.0006 },
  'openai/gpt-oss-20b': { input: 0.000075, output: 0.0003 },
}
